[2024-07-12T00:17:06.621+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion.ingest_task manual__2024-07-12T00:17:04.240558+00:00 [queued]>
[2024-07-12T00:17:06.627+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion.ingest_task manual__2024-07-12T00:17:04.240558+00:00 [queued]>
[2024-07-12T00:17:06.627+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-07-12T00:17:06.634+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonVirtualenvOperator): ingest_task> on 2024-07-12 00:17:04.240558+00:00
[2024-07-12T00:17:06.637+0000] {standard_task_runner.py:60} INFO - Started process 551 to run task
[2024-07-12T00:17:06.639+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion', 'ingest_task', 'manual__2024-07-12T00:17:04.240558+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmpt70pvfwy']
[2024-07-12T00:17:06.640+0000] {standard_task_runner.py:88} INFO - Job 8: Subtask ingest_task
[2024-07-12T00:17:06.648+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-07-12T00:17:06.661+0000] {task_command.py:423} INFO - Running <TaskInstance: data_ingestion.ingest_task manual__2024-07-12T00:17:04.240558+00:00 [running]> on host ***-scheduler
[2024-07-12T00:17:06.686+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion' AIRFLOW_CTX_TASK_ID='ingest_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-12T00:17:04.240558+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-12T00:17:04.240558+00:00'
[2024-07-12T00:17:07.093+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvm7h6kp9t --system-site-packages --python=python
[2024-07-12T00:17:07.101+0000] {process_utils.py:186} INFO - Output:
[2024-07-12T00:17:07.508+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.19.final.0-64 in 123ms
[2024-07-12T00:17:07.509+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venvm7h6kp9t, clear=False, no_vcs_ignore=False, global=True)
[2024-07-12T00:17:07.509+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-07-12T00:17:07.509+0000] {process_utils.py:190} INFO -     added seed packages: pip==24.0, setuptools==69.1.0, wheel==0.42.0
[2024-07-12T00:17:07.509+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-07-12T00:17:07.527+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvm7h6kp9t/bin/pip install -r /tmp/venvm7h6kp9t/requirements.txt
[2024-07-12T00:17:07.532+0000] {process_utils.py:186} INFO - Output:
[2024-07-12T00:17:08.254+0000] {process_utils.py:190} INFO - Requirement already satisfied: acryl-datahub==0.12.1.5 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvm7h6kp9t/requirements.txt (line 1)) (0.12.1.5)
[2024-07-12T00:17:10.392+0000] {process_utils.py:190} INFO - Requirement already satisfied: tabulate in /home/***/.local/lib/python3.8/site-packages (from acryl-datahub==0.12.1.5->-r /tmp/venvm7h6kp9t/requirements.txt (line 1)) (0.9.0)
[2024-07-12T00:17:10.396+0000] {process_utils.py:190} INFO - Requirement already satisfied: progressbar2 in /home/***/.local/lib/python3.8/site-packages (from acryl-datahub==0.12.1.5->-r /tmp/venvm7h6kp9t/requirements.txt (line 1)) (4.4.2)
[2024-07-12T00:17:10.397+0000] {process_utils.py:190} INFO - Requirement already satisfied: termcolor>=1.0.0 in /home/***/.local/lib/python3.8/site-packages (from acryl-datahub==0.12.1.5->-r /tmp/venvm7h6kp9t/requirements.txt (line 1)) (2.4.0)
[2024-07-12T00:17:10.400+0000] {process_utils.py:190} INFO - Requirement already satisfied: jsonref in /home/***/.local/lib/python3.8/site-packages (from acryl-datahub==0.12.1.5->-r /tmp/venvm7h6kp9t/requirements.txt (line 1)) (1.1.0)
[2024-07-12T00:17:10.402+0000] {process_utils.py:190} INFO - Requirement already satisfied: psutil>=5.8.0 in /home/***/.local/lib/python3.8/site-packages (from acryl-datahub==0.12.1.5->-r /tmp/venvm7h6kp9t/requirements.txt (line 1)) (5.9.8)
[2024-07-12T00:17:10.402+0000] {process_utils.py:190} INFO - Requirement already satisfied: Deprecated in /home/***/.local/lib/python3.8/site-packages (from acryl-datahub==0.12.1.5->-r /tmp/venvm7h6kp9t/requirements.txt (line 1)) (1.2.14)
[2024-07-12T00:17:10.403+0000] {process_utils.py:190} INFO - Requirement already satisfied: cached-property in /home/***/.local/lib/python3.8/site-packages (from acryl-datahub==0.12.1.5->-r /tmp/venvm7h6kp9t/requirements.txt (line 1)) (1.5.2)
[2024-07-12T00:17:10.404+0000] {process_utils.py:190} INFO - Requirement already satisfied: PyYAML in /home/***/.local/lib/python3.8/site-packages (from acryl-datahub==0.12.1.5->-r /tmp/venvm7h6kp9t/requirements.txt (line 1)) (6.0.1)
[2024-07-12T00:17:10.405+0000] {process_utils.py:190} INFO - Requirement already satisfied: pydantic!=1.10.3,>=1.10.0 in /home/***/.local/lib/python3.8/site-packages (from acryl-datahub==0.12.1.5->-r /tmp/venvm7h6kp9t/requirements.txt (line 1)) (2.8.2)
[2024-07-12T00:17:10.405+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests-file in /home/***/.local/lib/python3.8/site-packages (from acryl-datahub==0.12.1.5->-r /tmp/venvm7h6kp9t/requirements.txt (line 1)) (2.1.0)
[2024-07-12T00:17:10.406+0000] {process_utils.py:190} INFO - Requirement already satisfied: avro<1.12,>=1.11.3 in /home/***/.local/lib/python3.8/site-packages (from acryl-datahub==0.12.1.5->-r /tmp/venvm7h6kp9t/requirements.txt (line 1)) (1.11.3)
[2024-07-12T00:17:10.408+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging in /home/***/.local/lib/python3.8/site-packages (from acryl-datahub==0.12.1.5->-r /tmp/venvm7h6kp9t/requirements.txt (line 1)) (24.0)
[2024-07-12T00:17:10.412+0000] {process_utils.py:190} INFO - Requirement already satisfied: ijson in /home/***/.local/lib/python3.8/site-packages (from acryl-datahub==0.12.1.5->-r /tmp/venvm7h6kp9t/requirements.txt (line 1)) (3.2.3)
[2024-07-12T00:17:10.412+0000] {process_utils.py:190} INFO - Requirement already satisfied: docker in /home/***/.local/lib/python3.8/site-packages (from acryl-datahub==0.12.1.5->-r /tmp/venvm7h6kp9t/requirements.txt (line 1)) (7.0.0)
[2024-07-12T00:17:10.413+0000] {process_utils.py:190} INFO - Requirement already satisfied: sentry-sdk in /home/***/.local/lib/python3.8/site-packages (from acryl-datahub==0.12.1.5->-r /tmp/venvm7h6kp9t/requirements.txt (line 1)) (2.9.0)
[2024-07-12T00:17:10.413+0000] {process_utils.py:190} INFO - Requirement already satisfied: click-spinner in /home/***/.local/lib/python3.8/site-packages (from acryl-datahub==0.12.1.5->-r /tmp/venvm7h6kp9t/requirements.txt (line 1)) (0.1.10)
[2024-07-12T00:17:10.414+0000] {process_utils.py:190} INFO - Requirement already satisfied: mixpanel>=4.9.0 in /home/***/.local/lib/python3.8/site-packages (from acryl-datahub==0.12.1.5->-r /tmp/venvm7h6kp9t/requirements.txt (line 1)) (4.10.1)
[2024-07-12T00:17:10.414+0000] {process_utils.py:190} INFO - Requirement already satisfied: typing-inspect in /home/***/.local/lib/python3.8/site-packages (from acryl-datahub==0.12.1.5->-r /tmp/venvm7h6kp9t/requirements.txt (line 1)) (0.9.0)
[2024-07-12T00:17:10.415+0000] {process_utils.py:190} INFO - Requirement already satisfied: toml>=0.10.0 in /home/***/.local/lib/python3.8/site-packages (from acryl-datahub==0.12.1.5->-r /tmp/venvm7h6kp9t/requirements.txt (line 1)) (0.10.2)
[2024-07-12T00:17:10.415+0000] {process_utils.py:190} INFO - Requirement already satisfied: click>=7.1.2 in /home/***/.local/lib/python3.8/site-packages (from acryl-datahub==0.12.1.5->-r /tmp/venvm7h6kp9t/requirements.txt (line 1)) (8.1.7)
[2024-07-12T00:17:10.416+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil>=2.8.0 in /home/***/.local/lib/python3.8/site-packages (from acryl-datahub==0.12.1.5->-r /tmp/venvm7h6kp9t/requirements.txt (line 1)) (2.9.0.post0)
[2024-07-12T00:17:10.417+0000] {process_utils.py:190} INFO - Requirement already satisfied: humanfriendly in /home/***/.local/lib/python3.8/site-packages (from acryl-datahub==0.12.1.5->-r /tmp/venvm7h6kp9t/requirements.txt (line 1)) (10.0)
[2024-07-12T00:17:10.418+0000] {process_utils.py:190} INFO - Requirement already satisfied: click-default-group in /home/***/.local/lib/python3.8/site-packages (from acryl-datahub==0.12.1.5->-r /tmp/venvm7h6kp9t/requirements.txt (line 1)) (1.2.4)
[2024-07-12T00:17:10.418+0000] {process_utils.py:190} INFO - Requirement already satisfied: typing-extensions>=3.7.4.3 in /home/***/.local/lib/python3.8/site-packages (from acryl-datahub==0.12.1.5->-r /tmp/venvm7h6kp9t/requirements.txt (line 1)) (4.10.0)
[2024-07-12T00:17:10.419+0000] {process_utils.py:190} INFO - Requirement already satisfied: expandvars>=0.6.5 in /home/***/.local/lib/python3.8/site-packages (from acryl-datahub==0.12.1.5->-r /tmp/venvm7h6kp9t/requirements.txt (line 1)) (0.12.0)
[2024-07-12T00:17:10.420+0000] {process_utils.py:190} INFO - Requirement already satisfied: aiohttp<4 in /home/***/.local/lib/python3.8/site-packages (from acryl-datahub==0.12.1.5->-r /tmp/venvm7h6kp9t/requirements.txt (line 1)) (3.9.3)
[2024-07-12T00:17:10.420+0000] {process_utils.py:190} INFO - Requirement already satisfied: ruamel.yaml in /home/***/.local/lib/python3.8/site-packages (from acryl-datahub==0.12.1.5->-r /tmp/venvm7h6kp9t/requirements.txt (line 1)) (0.18.6)
[2024-07-12T00:17:10.421+0000] {process_utils.py:190} INFO - Requirement already satisfied: jsonschema in /home/***/.local/lib/python3.8/site-packages (from acryl-datahub==0.12.1.5->-r /tmp/venvm7h6kp9t/requirements.txt (line 1)) (4.21.1)
[2024-07-12T00:17:10.423+0000] {process_utils.py:190} INFO - Requirement already satisfied: avro-gen3==0.7.11 in /home/***/.local/lib/python3.8/site-packages (from acryl-datahub==0.12.1.5->-r /tmp/venvm7h6kp9t/requirements.txt (line 1)) (0.7.11)
[2024-07-12T00:17:10.425+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-metadata>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from acryl-datahub==0.12.1.5->-r /tmp/venvm7h6kp9t/requirements.txt (line 1)) (6.11.0)
[2024-07-12T00:17:10.425+0000] {process_utils.py:190} INFO - Requirement already satisfied: six in /home/***/.local/lib/python3.8/site-packages (from avro-gen3==0.7.11->acryl-datahub==0.12.1.5->-r /tmp/venvm7h6kp9t/requirements.txt (line 1)) (1.16.0)
[2024-07-12T00:17:10.426+0000] {process_utils.py:190} INFO - Requirement already satisfied: aiosignal>=1.1.2 in /home/***/.local/lib/python3.8/site-packages (from aiohttp<4->acryl-datahub==0.12.1.5->-r /tmp/venvm7h6kp9t/requirements.txt (line 1)) (1.3.1)
[2024-07-12T00:17:10.428+0000] {process_utils.py:190} INFO - Requirement already satisfied: attrs>=17.3.0 in /home/***/.local/lib/python3.8/site-packages (from aiohttp<4->acryl-datahub==0.12.1.5->-r /tmp/venvm7h6kp9t/requirements.txt (line 1)) (23.2.0)
[2024-07-12T00:17:10.428+0000] {process_utils.py:190} INFO - Requirement already satisfied: frozenlist>=1.1.1 in /home/***/.local/lib/python3.8/site-packages (from aiohttp<4->acryl-datahub==0.12.1.5->-r /tmp/venvm7h6kp9t/requirements.txt (line 1)) (1.4.1)
[2024-07-12T00:17:10.429+0000] {process_utils.py:190} INFO - Requirement already satisfied: multidict<7.0,>=4.5 in /home/***/.local/lib/python3.8/site-packages (from aiohttp<4->acryl-datahub==0.12.1.5->-r /tmp/venvm7h6kp9t/requirements.txt (line 1)) (6.0.5)
[2024-07-12T00:17:10.430+0000] {process_utils.py:190} INFO - Requirement already satisfied: yarl<2.0,>=1.0 in /home/***/.local/lib/python3.8/site-packages (from aiohttp<4->acryl-datahub==0.12.1.5->-r /tmp/venvm7h6kp9t/requirements.txt (line 1)) (1.9.4)
[2024-07-12T00:17:10.430+0000] {process_utils.py:190} INFO - Requirement already satisfied: async-timeout<5.0,>=4.0 in /home/***/.local/lib/python3.8/site-packages (from aiohttp<4->acryl-datahub==0.12.1.5->-r /tmp/venvm7h6kp9t/requirements.txt (line 1)) (4.0.3)
[2024-07-12T00:17:10.441+0000] {process_utils.py:190} INFO - Requirement already satisfied: zipp>=0.5 in /home/***/.local/lib/python3.8/site-packages (from importlib-metadata>=4.0.0->acryl-datahub==0.12.1.5->-r /tmp/venvm7h6kp9t/requirements.txt (line 1)) (3.18.1)
[2024-07-12T00:17:10.444+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests>=2.4.2 in /home/***/.local/lib/python3.8/site-packages (from mixpanel>=4.9.0->acryl-datahub==0.12.1.5->-r /tmp/venvm7h6kp9t/requirements.txt (line 1)) (2.31.0)
[2024-07-12T00:17:10.446+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3 in /home/***/.local/lib/python3.8/site-packages (from mixpanel>=4.9.0->acryl-datahub==0.12.1.5->-r /tmp/venvm7h6kp9t/requirements.txt (line 1)) (1.26.18)
[2024-07-12T00:17:10.457+0000] {process_utils.py:190} INFO - Requirement already satisfied: annotated-types>=0.4.0 in /home/***/.local/lib/python3.8/site-packages (from pydantic!=1.10.3,>=1.10.0->acryl-datahub==0.12.1.5->-r /tmp/venvm7h6kp9t/requirements.txt (line 1)) (0.7.0)
[2024-07-12T00:17:10.458+0000] {process_utils.py:190} INFO - Requirement already satisfied: pydantic-core==2.20.1 in /home/***/.local/lib/python3.8/site-packages (from pydantic!=1.10.3,>=1.10.0->acryl-datahub==0.12.1.5->-r /tmp/venvm7h6kp9t/requirements.txt (line 1)) (2.20.1)
[2024-07-12T00:17:10.487+0000] {process_utils.py:190} INFO - Requirement already satisfied: wrapt<2,>=1.10 in /home/***/.local/lib/python3.8/site-packages (from Deprecated->acryl-datahub==0.12.1.5->-r /tmp/venvm7h6kp9t/requirements.txt (line 1)) (1.16.0)
[2024-07-12T00:17:10.537+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-resources>=1.4.0 in /home/***/.local/lib/python3.8/site-packages (from jsonschema->acryl-datahub==0.12.1.5->-r /tmp/venvm7h6kp9t/requirements.txt (line 1)) (5.13.0)
[2024-07-12T00:17:10.537+0000] {process_utils.py:190} INFO - Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /home/***/.local/lib/python3.8/site-packages (from jsonschema->acryl-datahub==0.12.1.5->-r /tmp/venvm7h6kp9t/requirements.txt (line 1)) (2023.12.1)
[2024-07-12T00:17:10.538+0000] {process_utils.py:190} INFO - Requirement already satisfied: pkgutil-resolve-name>=1.3.10 in /home/***/.local/lib/python3.8/site-packages (from jsonschema->acryl-datahub==0.12.1.5->-r /tmp/venvm7h6kp9t/requirements.txt (line 1)) (1.3.10)
[2024-07-12T00:17:10.538+0000] {process_utils.py:190} INFO - Requirement already satisfied: referencing>=0.28.4 in /home/***/.local/lib/python3.8/site-packages (from jsonschema->acryl-datahub==0.12.1.5->-r /tmp/venvm7h6kp9t/requirements.txt (line 1)) (0.34.0)
[2024-07-12T00:17:10.539+0000] {process_utils.py:190} INFO - Requirement already satisfied: rpds-py>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from jsonschema->acryl-datahub==0.12.1.5->-r /tmp/venvm7h6kp9t/requirements.txt (line 1)) (0.18.0)
[2024-07-12T00:17:10.559+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-utils>=3.8.1 in /home/***/.local/lib/python3.8/site-packages (from progressbar2->acryl-datahub==0.12.1.5->-r /tmp/venvm7h6kp9t/requirements.txt (line 1)) (3.8.2)
[2024-07-12T00:17:10.585+0000] {process_utils.py:190} INFO - Requirement already satisfied: ruamel.yaml.clib>=0.2.7 in /home/***/.local/lib/python3.8/site-packages (from ruamel.yaml->acryl-datahub==0.12.1.5->-r /tmp/venvm7h6kp9t/requirements.txt (line 1)) (0.2.8)
[2024-07-12T00:17:10.671+0000] {process_utils.py:190} INFO - Requirement already satisfied: certifi in /home/***/.local/lib/python3.8/site-packages (from sentry-sdk->acryl-datahub==0.12.1.5->-r /tmp/venvm7h6kp9t/requirements.txt (line 1)) (2024.2.2)
[2024-07-12T00:17:10.676+0000] {process_utils.py:190} INFO - Requirement already satisfied: mypy-extensions>=0.3.0 in /home/***/.local/lib/python3.8/site-packages (from typing-inspect->acryl-datahub==0.12.1.5->-r /tmp/venvm7h6kp9t/requirements.txt (line 1)) (1.0.0)
[2024-07-12T00:17:10.732+0000] {process_utils.py:190} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests>=2.4.2->mixpanel>=4.9.0->acryl-datahub==0.12.1.5->-r /tmp/venvm7h6kp9t/requirements.txt (line 1)) (3.3.2)
[2024-07-12T00:17:10.732+0000] {process_utils.py:190} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests>=2.4.2->mixpanel>=4.9.0->acryl-datahub==0.12.1.5->-r /tmp/venvm7h6kp9t/requirements.txt (line 1)) (3.6)
[2024-07-12T00:17:12.518+0000] {process_utils.py:190} INFO - 
[2024-07-12T00:17:12.519+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 24.0 -> 24.1.2
[2024-07-12T00:17:12.519+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2024-07-12T00:17:12.653+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvm7h6kp9t/bin/python /tmp/venv-call6e6n__bs/script.py /tmp/venv-call6e6n__bs/script.in /tmp/venv-call6e6n__bs/script.out /tmp/venv-call6e6n__bs/string_args.txt /tmp/venv-call6e6n__bs/termination.log
[2024-07-12T00:17:12.682+0000] {process_utils.py:186} INFO - Output:
[2024-07-12T00:17:13.195+0000] {process_utils.py:190} INFO - /home/***/.local/lib/python3.8/site-packages/***/configuration.py:812 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-07-12T00:17:13.196+0000] {process_utils.py:190} INFO - /home/***/.local/lib/python3.8/site-packages/***/configuration.py:738 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-07-12T00:17:13.197+0000] {process_utils.py:190} INFO - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-07-12T00:17:13.416+0000] {process_utils.py:190} INFO - [[34m2024-07-12T00:17:13.414+0000[0m] {[34m__init__.py:[0m24} WARNING[0m -
[2024-07-12T00:17:13.422+0000] {process_utils.py:190} INFO -         OpenLineage support for Airflow version 2.8.4 is REMOVED.
[2024-07-12T00:17:13.425+0000] {process_utils.py:190} INFO -         For Airflow 2.7 and later, use the native Airflow Openlineage provider package.
[2024-07-12T00:17:13.425+0000] {process_utils.py:190} INFO -         Documentation can be found at https://***.apache.org/docs/apache-***-providers-openlineage
[2024-07-12T00:17:13.426+0000] {process_utils.py:190} INFO -         [0m
[2024-07-12T00:17:13.426+0000] {process_utils.py:190} INFO - /home/***/.local/lib/python3.8/site-packages/***/models/base.py:71 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-07-12T00:17:13.942+0000] {process_utils.py:190} INFO - [[34m2024-07-12T00:17:13.941+0000[0m] {[34mutils.py:[0m434} WARNING[0m - No module named '***.providers.dbt'[0m
[2024-07-12T00:17:14.314+0000] {process_utils.py:190} INFO - [[34m2024-07-12T00:17:14.313+0000[0m] {[34mbase.py:[0m83} INFO[0m - Using connection ID 'datahub_rest_default' for task execution.[0m
[2024-07-12T00:17:14.315+0000] {process_utils.py:190} INFO - [[34m2024-07-12T00:17:14.315+0000[0m] {[34mbase.py:[0m83} INFO[0m - Using connection ID 'datahub_rest_default' for task execution.[0m
[2024-07-12T00:17:14.315+0000] {process_utils.py:190} INFO - [[34m2024-07-12T00:17:14.315+0000[0m] {[34mdatahub_listener.py:[0m155} INFO[0m - DataHub plugin v2 using DataHubRestEmitter: configured to talk to http://datahub-gms:8080 with token: eyJh**********X0yk[0m
[2024-07-12T00:17:14.360+0000] {process_utils.py:190} INFO - [[34m2024-07-12T00:17:14.360+0000[0m] {[34mpipeline.py:[0m238} INFO[0m - Sink configured successfully. DataHubRestEmitter: configured to talk to http://datahub-gms:8080[0m
[2024-07-12T00:17:14.390+0000] {process_utils.py:190} INFO - Traceback (most recent call last):
[2024-07-12T00:17:14.390+0000] {process_utils.py:190} INFO -   File "/home/***/.local/lib/python3.8/site-packages/datahub/ingestion/api/registry.py", line 126, in _ensure_not_lazy
[2024-07-12T00:17:14.391+0000] {process_utils.py:190} INFO -     plugin_class = import_path(path)
[2024-07-12T00:17:14.391+0000] {process_utils.py:190} INFO -   File "/home/***/.local/lib/python3.8/site-packages/datahub/ingestion/api/registry.py", line 56, in import_path
[2024-07-12T00:17:14.391+0000] {process_utils.py:190} INFO -     item = importlib.import_module(module_name)
[2024-07-12T00:17:14.391+0000] {process_utils.py:190} INFO -   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
[2024-07-12T00:17:14.391+0000] {process_utils.py:190} INFO -     return _bootstrap._gcd_import(name[level:], package, level)
[2024-07-12T00:17:14.392+0000] {process_utils.py:190} INFO -   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
[2024-07-12T00:17:14.392+0000] {process_utils.py:190} INFO -   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
[2024-07-12T00:17:14.392+0000] {process_utils.py:190} INFO -   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
[2024-07-12T00:17:14.392+0000] {process_utils.py:190} INFO -   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
[2024-07-12T00:17:14.392+0000] {process_utils.py:190} INFO -   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
[2024-07-12T00:17:14.392+0000] {process_utils.py:190} INFO -   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
[2024-07-12T00:17:14.393+0000] {process_utils.py:190} INFO -   File "/home/***/.local/lib/python3.8/site-packages/datahub/ingestion/source/sql/mysql.py", line 3, in <module>
[2024-07-12T00:17:14.393+0000] {process_utils.py:190} INFO -     import pymysql  # noqa: F401
[2024-07-12T00:17:14.393+0000] {process_utils.py:190} INFO - ModuleNotFoundError: No module named 'pymysql'
[2024-07-12T00:17:14.393+0000] {process_utils.py:190} INFO - 
[2024-07-12T00:17:14.393+0000] {process_utils.py:190} INFO - The above exception was the direct cause of the following exception:
[2024-07-12T00:17:14.393+0000] {process_utils.py:190} INFO - 
[2024-07-12T00:17:14.393+0000] {process_utils.py:190} INFO - Traceback (most recent call last):
[2024-07-12T00:17:14.394+0000] {process_utils.py:190} INFO -   File "/home/***/.local/lib/python3.8/site-packages/datahub/ingestion/run/pipeline.py", line 121, in _add_init_error_context
[2024-07-12T00:17:14.394+0000] {process_utils.py:190} INFO -     yield
[2024-07-12T00:17:14.394+0000] {process_utils.py:190} INFO -   File "/home/***/.local/lib/python3.8/site-packages/datahub/ingestion/run/pipeline.py", line 248, in __init__
[2024-07-12T00:17:14.394+0000] {process_utils.py:190} INFO -     source_class = source_registry.get(source_type)
[2024-07-12T00:17:14.394+0000] {process_utils.py:190} INFO -   File "/home/***/.local/lib/python3.8/site-packages/datahub/ingestion/api/registry.py", line 176, in get
[2024-07-12T00:17:14.394+0000] {process_utils.py:190} INFO -     raise ConfigurationError(
[2024-07-12T00:17:14.394+0000] {process_utils.py:190} INFO - datahub.configuration.common.ConfigurationError: mysql is disabled; try running: pip install 'acryl-datahub[mysql]'
[2024-07-12T00:17:14.394+0000] {process_utils.py:190} INFO - 
[2024-07-12T00:17:14.395+0000] {process_utils.py:190} INFO - The above exception was the direct cause of the following exception:
[2024-07-12T00:17:14.395+0000] {process_utils.py:190} INFO - 
[2024-07-12T00:17:14.395+0000] {process_utils.py:190} INFO - Traceback (most recent call last):
[2024-07-12T00:17:14.395+0000] {process_utils.py:190} INFO -   File "/tmp/venv-call6e6n__bs/script.py", line 69, in <module>
[2024-07-12T00:17:14.395+0000] {process_utils.py:190} INFO -     res = ingest_from_mysql(*arg_dict["args"], **arg_dict["kwargs"])
[2024-07-12T00:17:14.395+0000] {process_utils.py:190} INFO -   File "/tmp/venv-call6e6n__bs/script.py", line 19, in ingest_from_mysql
[2024-07-12T00:17:14.395+0000] {process_utils.py:190} INFO -     pipeline = Pipeline.create(
[2024-07-12T00:17:14.395+0000] {process_utils.py:190} INFO -   File "/home/***/.local/lib/python3.8/site-packages/datahub/ingestion/run/pipeline.py", line 362, in create
[2024-07-12T00:17:14.396+0000] {process_utils.py:190} INFO -     return cls(
[2024-07-12T00:17:14.396+0000] {process_utils.py:190} INFO -   File "/home/***/.local/lib/python3.8/site-packages/datahub/ingestion/run/pipeline.py", line 248, in __init__
[2024-07-12T00:17:14.396+0000] {process_utils.py:190} INFO -     source_class = source_registry.get(source_type)
[2024-07-12T00:17:14.396+0000] {process_utils.py:190} INFO -   File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
[2024-07-12T00:17:14.396+0000] {process_utils.py:190} INFO -     self.gen.throw(type, value, traceback)
[2024-07-12T00:17:14.396+0000] {process_utils.py:190} INFO -   File "/home/***/.local/lib/python3.8/site-packages/datahub/ingestion/run/pipeline.py", line 123, in _add_init_error_context
[2024-07-12T00:17:14.397+0000] {process_utils.py:190} INFO -     raise PipelineInitError(f"Failed to {step}: {e}") from e
[2024-07-12T00:17:14.397+0000] {process_utils.py:190} INFO - datahub.ingestion.run.pipeline.PipelineInitError: Failed to find a registered source for type mysql: mysql is disabled; try running: pip install 'acryl-datahub[mysql]'
[2024-07-12T00:17:14.838+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 401, in execute
    return super().execute(context=serializable_context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 723, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 478, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
Failed to find a registered source for type mysql: mysql is disabled; try running: pip install 'acryl-datahub[mysql]'
[2024-07-12T00:17:14.844+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion, task_id=ingest_task, execution_date=20240712T001704, start_date=20240712T001706, end_date=20240712T001714
[2024-07-12T00:17:14.855+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 8 for task ingest_task (Process returned non-zero exit status 1.
Failed to find a registered source for type mysql: mysql is disabled; try running: pip install 'acryl-datahub[mysql]'; 551)
[2024-07-12T00:17:14.867+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-12T00:17:14.883+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
