[2024-07-02T05:44:36.757+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-02T05:44:36.762+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: adsasa.ingest_from_mysql manual__2024-07-02T05:39:33.701971+00:00 [queued]>
[2024-07-02T05:44:36.767+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: adsasa.ingest_from_mysql manual__2024-07-02T05:39:33.701971+00:00 [queued]>
[2024-07-02T05:44:36.767+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-02T05:44:36.773+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): ingest_from_mysql> on 2024-07-02 05:39:33.701971+00:00
[2024-07-02T05:44:36.777+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=542) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-02T05:44:36.778+0000] {standard_task_runner.py:63} INFO - Started process 545 to run task
[2024-07-02T05:44:36.777+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'adsasa', 'ingest_from_mysql', 'manual__2024-07-02T05:39:33.701971+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/adsasa.py', '--cfg-path', '/tmp/tmpzczi7tbu']
[2024-07-02T05:44:36.779+0000] {standard_task_runner.py:91} INFO - Job 36: Subtask ingest_from_mysql
[2024-07-02T05:44:36.784+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-07-02T05:44:36.803+0000] {task_command.py:426} INFO - Running <TaskInstance: adsasa.ingest_from_mysql manual__2024-07-02T05:39:33.701971+00:00 [running]> on host ***-scheduler
[2024-07-02T05:44:36.850+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='adsasa' AIRFLOW_CTX_TASK_ID='ingest_from_mysql' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T05:39:33.701971+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-02T05:39:33.701971+00:00'
[2024-07-02T05:44:37.073+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-02T05:44:37.150+0000] {pipeline.py:257} INFO - Sink configured successfully. DataHubRestEmitter: configured to talk to http://datahub-gms:8080
[2024-07-02T05:44:37.176+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-02T05:44:37.291+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/datahub/ingestion/api/registry.py", line 126, in _ensure_not_lazy
    plugin_class = import_path(path)
                   ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/datahub/ingestion/api/registry.py", line 56, in import_path
    item = importlib.import_module(module_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/datahub/ingestion/source/sql/mariadb.py", line 9, in <module>
    from datahub.ingestion.source.sql.mysql import MySQLConfig, MySQLSource
  File "/home/airflow/.local/lib/python3.12/site-packages/datahub/ingestion/source/sql/mysql.py", line 3, in <module>
    import pymysql  # noqa: F401
    ^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'pymysql'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/datahub/ingestion/run/pipeline.py", line 124, in _add_init_error_context
    yield
  File "/home/airflow/.local/lib/python3.12/site-packages/datahub/ingestion/run/pipeline.py", line 272, in __init__
    source_class = source_registry.get(self.source_type)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/datahub/ingestion/api/registry.py", line 176, in get
    raise ConfigurationError(
datahub.configuration.common.ConfigurationError: mariadb is disabled; try running: pip install 'acryl-datahub[mariadb]'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/adsasa.py", line 75, in ingest_from_mysql
    pipeline = Pipeline.create(
               ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/datahub/ingestion/run/pipeline.py", line 393, in create
    return cls(
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/datahub/ingestion/run/pipeline.py", line 269, in __init__
    with _add_init_error_context(
  File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/home/airflow/.local/lib/python3.12/site-packages/datahub/ingestion/run/pipeline.py", line 128, in _add_init_error_context
    raise PipelineInitError(f"Failed to {step}: {e}") from e
datahub.ingestion.run.pipeline.PipelineInitError: Failed to find a registered source for type mariadb: mariadb is disabled; try running: pip install 'acryl-datahub[mariadb]'
[2024-07-02T05:44:37.304+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=adsasa, task_id=ingest_from_mysql, run_id=manual__2024-07-02T05:39:33.701971+00:00, execution_date=20240702T053933, start_date=20240702T054436, end_date=20240702T054437
[2024-07-02T05:44:37.311+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 36 for task ingest_from_mysql (Failed to find a registered source for type mariadb: mariadb is disabled; try running: pip install 'acryl-datahub[mariadb]'; 545)
[2024-07-02T05:44:37.326+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-02T05:44:37.336+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-02T05:44:37.336+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
